//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLocamer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public string nomCli { get; set; }
        public string prenomCli { get; set; }
        public string adresseCli { get; set; }
        public string mailCli { get; set; }
        public string telCli { get; set; }
        public int idCli { get; set; }
        public Nullable<int> idSejour { get; set; }
    
        public virtual sejour sejour { get; set; }
    }
}
