//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLocamer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sejour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sejour()
        {
            this.clients = new HashSet<client>();
            this.mobilomes = new HashSet<mobilome>();
        }
    
        public int idSejour { get; set; }
        public Nullable<System.DateTime> dateDeb { get; set; }
        public Nullable<System.DateTime> dateFin { get; set; }
        public Nullable<int> idOption { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client> clients { get; set; }
        public virtual option option { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobilome> mobilomes { get; set; }
    }
}
